### ISSUE TITLE
Nicht kompatibel mir 4.11.x

### ISSUE THREAD

**Issue by hinzke** [netzmacht/html#6] opened 2021-06-24 13:01 UTC
Das Plugin ist leider nicht mit 4.11.x kompatibel
Beim Update erhält man folgenden Fehler

> $ /usr/bin/php -q -dmax_execution_time=0 -dmemory_limit=-1 -dallow_url_fopen=1 -ddisable_functions= -ddate.timezone=Europe/Berlin /kunden/XXXX/rp-hosting/XXXX/0160/domain.de/domain.de/vendor/contao/manager-bundle/bin/contao-console cache:clear --env=prod --no-warmup
> 
> PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /kunden/XXXX/rp-hosting/XXXX/0160/domain.de/domain.de/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php on line 32 and at least 1 expected in /kunden/XXXX/rp-hosting/XXXX/0160/domain.de/domain.de/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
> Stack trace:
> #0 /kunden/XXXX/rp-hosting/XXXX/0160/domain.de/domain.de/vendor/netzmacht/html/src/Infrastructure/SymfonyBundle/DependencyInjection/Configuration.php(32): Symfony\Component\Config\Definition\Builder\TreeBuilder->__construct()
> #1 /kunden/XXXX/rp-hosting/XXXX/0160/domain.de/domain.de/vendor/symfony/config/Definition/Processor.php(50): Netzmacht\Html\Infrastructure\SymfonyBundle\DependencyInjection\Configuration->getConfigTreeBuilder()
> #2 /kunden/XXXX/rp-hosting/XXXX/0160/domain.de/domain.de/vendor/symfony/dependency in /kunden/XXXX/rp-hosting/XXXX/0160/domain.de/domain.de/vendor/symfony/config/Definition/Builder/TreeBuilder.php on line 26
> 
> # Process terminated with exit code 255
> # Result: Unknown error

**Comment by fritzmg** [comment] 2021-06-24 13:58
As already mentioned on the Contao forum, the problem is not Contao 4.11. The module in its current state is incompatible with _Symfony_ 5. You can work around it by downgrading `symfony/config` to `^4.4`.

**Comment by dmolineus** [comment] 2021-09-15 12:04
Fixed with version 2.0.2

**Closed by dmolineus** 2021-09-15 12:04 UTC
